export const categoryData = [
  {
    title: 'Western Wear',
    category: 'clothing',
    type: 'western',
    for: 'women',
    key: 5,
    discount: 30,
    image: 'https://www.aachho.com/cdn/shop/products/43_0bdcc1af-721d-412c-a566-2c178a8bda5c_540x.png?v=1684511050',
  },
  {
    title: 'Sleep Wear',
    category: 'clothing',
    for: 'women',
    type: 'sleep-wear',
    key: 5,
    discount: 35,
    image:
      'https://www.wallacecotton.com/content/products/pippa-organic-cotton-knit-pj-shirt-floral-5-9398.jpg?width=1120',
  },
  {
    title: 'Work Wear',
    category: 'clothing',
    for: 'men',
    type: 'formal',
    key: 5,
    discount: 23,
    image: 'https://i.pinimg.com/564x/73/6d/99/736d99b5612c692dfa0b4a57f4136303.jpg',
  },
  {
    title: 'Casual Wear',
    category: 'clothing',
    type: 'casual',
    key: 4,
    for: 'men',
    discount: 20,
    image: 'https://mensflair.com/wp-content/uploads/2022/06/smart-casual-footwear-1-500x750.jpg',
  },
  {
    title: 'Hand Bags',
    category: 'bags',
    type: 'casual',
    for: 'women',
    key: 5,
    discount: 50,
    image:
      'https://www.jiomart.com/images/product/original/rvaoirokiu/lafille-latest-croco-texture-handbags-for-women-girls-ladies-purse-tote-bag-handbags-for-office-college-black-dgn241-product-images-rvaoirokiu-0-202301141634.jpg?im=Resize=(500,630)',
  },
  {
    title: 'Footwear',
    category: 'footwear',
    type: 'all',
    for: 'men',
    key: 1,
    discount: 15,
    image:
      'https://assets.ajio.com/medias/sys_master/root/20230927/cJMo/651384dcddf7791519052924/-1117Wx1400H-466640921-white-MODEL.jpg',
  },
  {
    title: 'Ethnic Wear',
    category: 'clothing',
    type: 'ethnic',
    for: 'women',
    key: 2,
    discount: 10,
    image: 'https://img3.junaroad.com/uiproducts/18575840/zoom_0-1665384448.jpg',
  },
  {
    title: 'Sports Wear',
    for: 'women',
    category: 'clothing',
    type: 'sport',
    key: 3,
    discount: 25,
    image:
      'https://blog.playo.co/wp-content/uploads/2019/02/women-Sportswear-Training-Running-Tights-Sports-Suit-Women-Yoga-Clothes-Fitting-Gym-Wicking-Compression-Jogging-sets.jpg_640x640.jpg',
  },
  {
    title: 'Western Wear',
    category: 'clothing',
    type: 'western',
    for: 'women',
    key: 5,
    discount: 30,
    image: 'https://www.aachho.com/cdn/shop/products/43_0bdcc1af-721d-412c-a566-2c178a8bda5c_540x.png?v=1684511050',
  },
  {
    title: 'Sleep Wear',
    category: 'clothing',
    for: 'women',
    type: 'sleep-wear',
    key: 5,
    discount: 35,
    image:
      'https://www.wallacecotton.com/content/products/pippa-organic-cotton-knit-pj-shirt-floral-5-9398.jpg?width=1120',
  },
]
